### ISSUE TITLE
Launcher icon hard to find with gnome-shell (for snap install)

### ISSUE THREAD

**Issue by dalanicolai** [MicroPad/MicroPad-Electron#16]
When trying to open micropad via gnome-shell, the launcher is not shown when searching on 'micropad' or 'pad'. The μ symbol has to be typed explicitily.

**Comment by dalanicolai** [comment]
just adding micropad in the comment of the .desktop file solves this issue btw.

**Comment by NickGeek** [comment]
Oh neat. If you make a pull request I can merge it in now, if not I’ll get to this as soon as I can.

Thanks!
