### ISSUE TITLE
Allow turning of the spell checker

### ISSUE THREAD

**Issue by Banbury** [MicroPad/MicroPad-Electron#17]
**Is your feature request related to a problem? Please describe.**
I'm writing in German. So almost every word is underlined in red. This is very distracting.

**Describe the solution you'd like**
An option to turn off the spell checker and/or a German dictionary.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Banbury** [comment]
Yes, I'm using the Electron version.

**Comment by NickGeek** [comment]
@Banbury I've just released v3.16.3 for Windows, macOS, and Linux. As well as including MicroPad v3.16.3 it also includes the spell-check disable.

**Comment by Banbury** [comment]
That was quick. Thanks!

**Comment by NickGeek** [comment]
No problem :-)
