### ISSUE TITLE
App does not run on MacOS High Sierra 10.12.6

### ISSUE THREAD

**Issue by malsmith** [MicroPad/MicroPad-Electron#2]
I built the Electron app on my mac.  When I run the DMG installed or directly from the 

dist/mac/µPad.app/Contents/MacOS/µPad 

I get this error 

/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5 

and only a blank window displays in the GUI.

Seems related to these bugs 

https://github.com/electron/electron/issues/10559

**Comment by NickGeek** [comment]
Thanks for the report. It seems to work fine for me on my mac with High Sierra, but I can look into it.

**Comment by NickGeek** [comment]
@malsmith Hey, could you please try installing https://github.com/MicroPad/Electron/releases/download/v3.8.2/micropad-3.8.2.dmg and seeing if the problem is fixed for you with that?
