### ISSUE TITLE
Windows: choose where to install MicroPad

### ISSUE THREAD

**Issue by AndrewMD888** [MicroPad/MicroPad-Electron#20]
I noticed that when installing MicroPad on Windows 10 using the installer tool, it installs into a location on the storage device that isn't the most desirable. It installs into the AppData folder which is tucked away and also a hidden item in Windows. Made it hard to find the software's contents when searching for them. It would be good if the user could specify the installation directory upon installation, as right now no set-up options exist upon first install. The program just installs and runs.

**Comment by NickGeek** [comment]
I'll see what I can do. I use an electron packager to build the windows installer but I'm sure I can get it to do something a little more custom.

**Comment by NickGeek** [comment]
https://github.com/MicroPad/MicroPad-Electron/releases/download/v3.30.6/micropad-setup-3.30.6.exe should help you out here
