### ISSUE TITLE
Feature Request: New note should open under the mouse

### ISSUE THREAD

**Issue by yuxi-liu-wired** [MicroPad/MicroPad-Electron#24]
The same request https://github.com/MicroPad/Web/issues/165

Pressing "n" opens a new note at the top left corner, which I must then manually drag to the right position. This is particularly frustrating when the canvas is big. It should open the new note right under the mouse.

This can't be implemented in browser because browser won't reveal mouse location, but it might be implementable on desktop.

**Comment by NickGeek** [comment]
This has been done in MicroPad v4. See https://next.getmicropad.com for a preview of v4, which will be fully launching soon.
