### ISSUE TITLE
Electron doesn't have the Chrome PDF viewer enabled for some reason

### ISSUE THREAD

**Issue by NickGeek** [MicroPad/MicroPad-Electron#27]
https://github.com/electron/electron/issues/12337

**Comment by MiXT4PE** [comment]
Isn't this a duplicate of https://github.com/electron/electron/issues/12337?

**Comment by NickGeek** [comment]
Resolved in the latest release

**Comment by DanielJackson-Oslo** [comment]
Sorry to interrupt this project, but @NickGeek How did you resolve this?

**Comment by DanielJackson-Oslo** [comment]
Just found it in the code base. Sorry for not looking earlier. You ended up using pdfjs instead?

**Comment by NickGeek** [comment]
No problem at all. Yes, I ended up forcing pdfjs when electron is being used.
