### ISSUE TITLE
Feature Request : Save as in the select folder the notepad created

### ISSUE THREAD

**Issue by Caiuzx** [MicroPad/MicroPad-Electron#35]
Select a folder for my notepad saved on hard disk.
now are on Appdata/Roaming/micropad
thank you

**Comment by NickGeek** [comment]
You can go Ctrl+S to save a notebook, Ctrl+O to open one from the hard disk and in the notebooks menu there is an option to save all of your notebooks to a file.

**Comment by Caiuzx** [comment]
ok thanks
