### ISSUE TITLE
Remember the last state of MicroPad window

### ISSUE THREAD

**Issue by AndrewMD888** [MicroPad/MicroPad-Electron#42]
This is a small but helpful feature - it would be handy if the program opened to the same window size/position upon start up that it had from the previous execution.

**Comment by zoepicone** [comment]
I can try working on this - seems like window.js in [electron-boilerplate](https://github.com/szwacz/electron-boilerplate) would be able to deal with this pretty easily

**Comment by NickGeek** [comment]
@zoedelphi That works although by the looks of it, you could probably use the nodejs `fs/promises` package directly to store the setting as JSON or something. It looks small enough to implement that I think a whole lib might be overkill?

1. If the file exists upon loading the app then parse it
2. If error skip
3. If it parses correctly then call the electron `setSize` function on BrowserWindow (https://www.electronjs.org/docs/latest/api/browser-window#winsetsizewidth-height-animate) to that value
4. Add an event handler for the resize event to update and save that file asynchronously

**Comment by zoepicone** [comment]
@NickGeek I think the main issue would be dealing with resolution changes that could leave the window inaccessible due to being completely out of bounds - I was just thinking of using the single js file as nothing else in the lib is needed

**Comment by NickGeek** [comment]
@zoedelphi fair enough. As long as the licencing is okay with that file. You'll want to watch out for extra deps they pull in too. If you send in a PR I'll take a look.

**Comment by NickGeek** [comment]
Fixed in v4
